"""initial schema

Revision ID: 49a48ada587e
Revises: 
Create Date: 2026-04-24 12:29:45.733091+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49a48ada587e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic', sa.String(length=256), nullable=False),
    sa.Column('creator_pubkey', sa.LargeBinary(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('turn_owner_pubkey', sa.LargeBinary(length=32), nullable=True),
    sa.Column('turn_n', sa.Integer(), nullable=False),
    sa.Column('max_turns', sa.Integer(), nullable=False),
    sa.Column('ttl_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_by_pubkey', sa.LargeBinary(length=32), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('author_pubkey', sa.LargeBinary(length=32), nullable=False),
    sa.Column('turn_n', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sig', sa.LargeBinary(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'turn_n', name='uq_messages_room_turn')
    )
    op.create_index(op.f('ix_messages_room_id'), 'messages', ['room_id'], unique=False)
    op.create_table('participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('agent_pubkey', sa.LargeBinary(length=32), nullable=False),
    sa.Column('owner_pubkey', sa.LargeBinary(length=32), nullable=False),
    sa.Column('invited_by_pubkey', sa.LargeBinary(length=32), nullable=False),
    sa.Column('invited_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accept_sig', sa.LargeBinary(length=64), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'agent_pubkey', name='uq_participants_room_agent')
    )
    op.create_index(op.f('ix_participants_room_id'), 'participants', ['room_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_participants_room_id'), table_name='participants')
    op.drop_table('participants')
    op.drop_index(op.f('ix_messages_room_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_table('rooms')
    # ### end Alembic commands ###
